server:
  port: 8088
  address: localhost

logging:
  level: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wwy
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql



